apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-service
  name: inventory-service
  namespace: monitoring
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 7070
    protocol: TCP
    targetPort: 7070
  selector:
    app: inventory-service
  sessionAffinity: None
  type: ClusterIP
